#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyageVistaSales.Plugins.Models
{
	
	
	/// <summary>
	/// Status of the Travel Inquiry
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum voy_travelinquiry_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Travel Inquiry
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum voy_travelinquiry_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		New = 629350001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InProgress = 629350002,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ConvertedtoQuote = 629350003,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Closed = 629350004,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("voy_travelinquiry")]
	public partial class voy_TravelInquiry : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public voy_TravelInquiry() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "voy_travelinquiry";
		
		public const string EntityLogicalCollectionName = "voy_travelinquiries";
		
		public const string EntitySetName = "voy_travelinquiries";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the entity with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> processid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			set
			{
				this.OnPropertyChanging("processid");
				this.SetAttributeValue("processid", value);
				this.OnPropertyChanged("processid");
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> stageid
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			set
			{
				this.OnPropertyChanging("stageid");
				this.SetAttributeValue("stageid", value);
				this.OnPropertyChanged("stageid");
			}
		}
		
		/// <summary>
		/// Status of the Travel Inquiry
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual voy_travelinquiry_statecode? statecode
		{
			get
			{
				return ((voy_travelinquiry_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Travel Inquiry
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual voy_travelinquiry_statuscode? statuscode
		{
			get
			{
				return ((voy_travelinquiry_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string traversedpath
		{
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			set
			{
				this.OnPropertyChanging("traversedpath");
				this.SetAttributeValue("traversedpath", value);
				this.OnPropertyChanged("traversedpath");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_budget")]
		public Microsoft.Xrm.Sdk.Money voy_Budget
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("voy_budget");
			}
			set
			{
				this.OnPropertyChanging("voy_Budget");
				this.SetAttributeValue("voy_budget", value);
				this.OnPropertyChanged("voy_Budget");
			}
		}
		
		/// <summary>
		/// Value of the Budget in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_budget_base")]
		public Microsoft.Xrm.Sdk.Money voy_budget_Base
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("voy_budget_base");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_customerid")]
		public Microsoft.Xrm.Sdk.EntityReference voy_CustomerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("voy_customerid");
			}
			set
			{
				this.OnPropertyChanging("voy_CustomerId");
				this.SetAttributeValue("voy_customerid", value);
				this.OnPropertyChanged("voy_CustomerId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_destination")]
		public string voy_Destination
		{
			get
			{
				return this.GetAttributeValue<string>("voy_destination");
			}
			set
			{
				this.OnPropertyChanging("voy_Destination");
				this.SetAttributeValue("voy_destination", value);
				this.OnPropertyChanged("voy_Destination");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_enddate")]
		public System.Nullable<System.DateTime> voy_EndDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("voy_enddate");
			}
			set
			{
				this.OnPropertyChanging("voy_EndDate");
				this.SetAttributeValue("voy_enddate", value);
				this.OnPropertyChanged("voy_EndDate");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_name")]
		public string voy_Name
		{
			get
			{
				return this.GetAttributeValue<string>("voy_name");
			}
			set
			{
				this.OnPropertyChanging("voy_Name");
				this.SetAttributeValue("voy_name", value);
				this.OnPropertyChanged("voy_Name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_numberoftravelers")]
		public System.Nullable<int> voy_Numberoftravelers
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("voy_numberoftravelers");
			}
			set
			{
				this.OnPropertyChanging("voy_Numberoftravelers");
				this.SetAttributeValue("voy_numberoftravelers", value);
				this.OnPropertyChanged("voy_Numberoftravelers");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_startdate")]
		public System.Nullable<System.DateTime> voy_StartDate
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("voy_startdate");
			}
			set
			{
				this.OnPropertyChanging("voy_StartDate");
				this.SetAttributeValue("voy_startdate", value);
				this.OnPropertyChanged("voy_StartDate");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_travelinquiryid")]
		public System.Nullable<System.Guid> voy_TravelInquiryId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("voy_travelinquiryid");
			}
			set
			{
				this.OnPropertyChanging("voy_TravelInquiryId");
				this.SetAttributeValue("voy_travelinquiryid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("voy_TravelInquiryId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_travelinquiryid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.voy_TravelInquiryId = value;
			}
		}
		
		/// <summary>
		/// 1:N voy_quote_TravelInquiryId_voy_travelinquiry
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("voy_quote_TravelInquiryId_voy_travelinquiry")]
		public System.Collections.Generic.IEnumerable<VoyageVistaSales.Plugins.Models.voy_Quote> voy_quote_TravelInquiryId_voy_travelinquiry
		{
			get
			{
				return this.GetRelatedEntities<VoyageVistaSales.Plugins.Models.voy_Quote>("voy_quote_TravelInquiryId_voy_travelinquiry", null);
			}
			set
			{
				this.OnPropertyChanging("voy_quote_TravelInquiryId_voy_travelinquiry");
				this.SetRelatedEntities<VoyageVistaSales.Plugins.Models.voy_Quote>("voy_quote_TravelInquiryId_voy_travelinquiry", null, value);
				this.OnPropertyChanged("voy_quote_TravelInquiryId_voy_travelinquiry");
			}
		}
		
		/// <summary>
		/// N:1 voy_account_voy_travelinquiry_accountid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("voy_account_voy_travelinquiry_accountid")]
		public VoyageVistaSales.Plugins.Models.Account voy_account_voy_travelinquiry_accountid
		{
			get
			{
				return this.GetRelatedEntity<VoyageVistaSales.Plugins.Models.Account>("voy_account_voy_travelinquiry_accountid", null);
			}
			set
			{
				this.OnPropertyChanging("voy_account_voy_travelinquiry_accountid");
				this.SetRelatedEntity<VoyageVistaSales.Plugins.Models.Account>("voy_account_voy_travelinquiry_accountid", null, value);
				this.OnPropertyChanged("voy_account_voy_travelinquiry_accountid");
			}
		}
		
		/// <summary>
		/// N:1 voy_contact_voy_travelinquiry_contactid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("voy_contact_voy_travelinquiry_contactid")]
		public VoyageVistaSales.Plugins.Models.Contact voy_contact_voy_travelinquiry_contactid
		{
			get
			{
				return this.GetRelatedEntity<VoyageVistaSales.Plugins.Models.Contact>("voy_contact_voy_travelinquiry_contactid", null);
			}
			set
			{
				this.OnPropertyChanging("voy_contact_voy_travelinquiry_contactid");
				this.SetRelatedEntity<VoyageVistaSales.Plugins.Models.Contact>("voy_contact_voy_travelinquiry_contactid", null, value);
				this.OnPropertyChanged("voy_contact_voy_travelinquiry_contactid");
			}
		}
	}
}
#pragma warning restore CS1591
