#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyageVistaSales.Plugins.Models
{
	
	
	/// <summary>
	/// Status of the Quote Line Item
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum voy_quotelineitem_statecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Reason for the status of the Quote Line Item
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum voy_quotelineitem_statuscode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 2,
	}
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("voy_quotelineitem")]
	public partial class voy_QuoteLineItem : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		public voy_QuoteLineItem() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "voy_quotelineitem";
		
		public const string EntityLogicalCollectionName = "voy_quotelineitems";
		
		public const string EntitySetName = "voy_quotelineitems";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Quote Line Item
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public virtual voy_quotelineitem_statecode? statecode
		{
			get
			{
				return ((voy_quotelineitem_statecode?)(EntityOptionSetEnum.GetEnum(this, "statecode")));
			}
			set
			{
				this.OnPropertyChanging("statecode");
				this.SetAttributeValue("statecode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Quote Line Item
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public virtual voy_quotelineitem_statuscode? statuscode
		{
			get
			{
				return ((voy_quotelineitem_statuscode?)(EntityOptionSetEnum.GetEnum(this, "statuscode")));
			}
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value.HasValue ? new Microsoft.Xrm.Sdk.OptionSetValue((int)value) : null);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_amount")]
		public System.Nullable<int> voy_Amount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("voy_amount");
			}
			set
			{
				this.OnPropertyChanging("voy_Amount");
				this.SetAttributeValue("voy_amount", value);
				this.OnPropertyChanged("voy_Amount");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_description")]
		public string voy_Description
		{
			get
			{
				return this.GetAttributeValue<string>("voy_description");
			}
			set
			{
				this.OnPropertyChanging("voy_Description");
				this.SetAttributeValue("voy_description", value);
				this.OnPropertyChanged("voy_Description");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_discountamount")]
		public System.Nullable<decimal> voy_DiscountAmount
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("voy_discountamount");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_discountpercentage")]
		public System.Nullable<int> voy_DiscountPercentage
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("voy_discountpercentage");
			}
			set
			{
				this.OnPropertyChanging("voy_DiscountPercentage");
				this.SetAttributeValue("voy_discountpercentage", value);
				this.OnPropertyChanged("voy_DiscountPercentage");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_name")]
		public string voy_Name
		{
			get
			{
				return this.GetAttributeValue<string>("voy_name");
			}
			set
			{
				this.OnPropertyChanging("voy_Name");
				this.SetAttributeValue("voy_name", value);
				this.OnPropertyChanged("voy_Name");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_priceperunit")]
		public System.Nullable<decimal> voy_PricePerUnit
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("voy_priceperunit");
			}
			set
			{
				this.OnPropertyChanging("voy_PricePerUnit");
				this.SetAttributeValue("voy_priceperunit", value);
				this.OnPropertyChanged("voy_PricePerUnit");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_quoteid")]
		public Microsoft.Xrm.Sdk.EntityReference voy_QuoteId
		{
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("voy_quoteid");
			}
			set
			{
				this.OnPropertyChanging("voy_QuoteId");
				this.SetAttributeValue("voy_quoteid", value);
				this.OnPropertyChanged("voy_QuoteId");
			}
		}
		
		/// <summary>
		/// Unique identifier for entity instances
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_quotelineitemid")]
		public System.Nullable<System.Guid> voy_QuoteLineItemId
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("voy_quotelineitemid");
			}
			set
			{
				this.OnPropertyChanging("voy_QuoteLineItemId");
				this.SetAttributeValue("voy_quotelineitemid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("voy_QuoteLineItemId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_quotelineitemid")]
		public override System.Guid Id
		{
			get
			{
				return base.Id;
			}
			set
			{
				this.voy_QuoteLineItemId = value;
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_total")]
		public System.Nullable<decimal> voy_Total
		{
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("voy_total");
			}
		}
		
		/// <summary>
		/// N:1 voy_Quote_voy_QuoteId_voy_QuoteLineItem
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("voy_quoteid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("voy_Quote_voy_QuoteId_voy_QuoteLineItem")]
		public VoyageVistaSales.Plugins.Models.voy_Quote voy_Quote_voy_QuoteId_voy_QuoteLineItem
		{
			get
			{
				return this.GetRelatedEntity<VoyageVistaSales.Plugins.Models.voy_Quote>("voy_Quote_voy_QuoteId_voy_QuoteLineItem", null);
			}
			set
			{
				this.OnPropertyChanging("voy_Quote_voy_QuoteId_voy_QuoteLineItem");
				this.SetRelatedEntity<VoyageVistaSales.Plugins.Models.voy_Quote>("voy_Quote_voy_QuoteId_voy_QuoteLineItem", null, value);
				this.OnPropertyChanged("voy_Quote_voy_QuoteId_voy_QuoteLineItem");
			}
		}
	}
}
#pragma warning restore CS1591
