#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyageVistaSales.Plugins.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.RequestProxyAttribute("voy_CalculateQuoteTotal")]
	public partial class voy_CalculateQuoteTotalRequest : Microsoft.Xrm.Sdk.OrganizationRequest
	{
		
		public System.Guid QuoteId
		{
			get
			{
				if (this.Parameters.Contains("QuoteId"))
				{
					return ((System.Guid)(this.Parameters["QuoteId"]));
				}
				else
				{
					return default(System.Guid);
				}
			}
			set
			{
				this.Parameters["QuoteId"] = value;
			}
		}
		
		public Microsoft.Xrm.Sdk.EntityReference Target
		{
			get
			{
				if (this.Parameters.Contains("Target"))
				{
					return ((Microsoft.Xrm.Sdk.EntityReference)(this.Parameters["Target"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.EntityReference);
				}
			}
			set
			{
				this.Parameters["Target"] = value;
			}
		}
		
		public voy_CalculateQuoteTotalRequest()
		{
			this.RequestName = "voy_CalculateQuoteTotal";
			this.QuoteId = default(System.Guid);
			this.Target = default(Microsoft.Xrm.Sdk.EntityReference);
		}
	}
	
	[System.Runtime.Serialization.DataContractAttribute(Namespace="http://schemas.microsoft.com/xrm/2011/new/")]
	[Microsoft.Xrm.Sdk.Client.ResponseProxyAttribute("voy_CalculateQuoteTotal")]
	public partial class voy_CalculateQuoteTotalResponse : Microsoft.Xrm.Sdk.OrganizationResponse
	{
		
		public voy_CalculateQuoteTotalResponse()
		{
		}
		
		public Microsoft.Xrm.Sdk.Money TotalAmount
		{
			get
			{
				if (this.Results.Contains("TotalAmount"))
				{
					return ((Microsoft.Xrm.Sdk.Money)(this.Results["TotalAmount"]));
				}
				else
				{
					return default(Microsoft.Xrm.Sdk.Money);
				}
			}
			set
			{
				this.Results["TotalAmount"] = value;
			}
		}
	}
}
#pragma warning restore CS1591
