// Generated by Dataverse PowerTools — shared harness for replaying captured plugin profiles (#63/#210).
// A profile is base64( raw-DEFLATE( <Report> XML ) ); its <Context> element is a DataContract-serialized
// PluginExecutionContext. This deserializes it into an IPluginExecutionContext and builds the plugin's
// IServiceProvider, so a generated Replay_*.cs can run your plugin IN-PROCESS with the real captured
// context. Uses only Microsoft.Xrm.Sdk — runs under dotnet test / Test Explorer with breakpoints.
using System;
using System.IO;
using System.IO.Compression;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Xml;
using System.Xml.Linq;
using Microsoft.Xrm.Sdk;
using Microsoft.Xrm.Sdk.Query;

namespace DvptReplay
{
    [DataContract(Name = "PluginExecutionContext", Namespace = "")]
    internal class CapturedPluginContext : IPluginExecutionContext
    {
        [DataMember] public Guid BusinessUnitId { get; set; }
        [DataMember] public Guid CorrelationId { get; set; }
        [DataMember] public int Depth { get; set; }
        [DataMember] public Guid InitiatingUserId { get; set; }
        [DataMember] public ParameterCollection InputParameters { get; set; }
        [DataMember] public bool IsExecutingOffline { get; set; }
        [DataMember] public bool IsInTransaction { get; set; }
        [DataMember] public bool IsOfflinePlayback { get; set; }
        [DataMember] public int IsolationMode { get; set; }
        [DataMember] public string MessageName { get; set; }
        [DataMember] public int Mode { get; set; }
        [DataMember] public DateTime OperationCreatedOn { get; set; }
        [DataMember] public Guid OperationId { get; set; }
        [DataMember] public Guid OrganizationId { get; set; }
        [DataMember] public string OrganizationName { get; set; }
        [DataMember] public ParameterCollection OutputParameters { get; set; }
        [DataMember] public EntityReference OwningExtension { get; set; }
        [DataMember] public EntityImageCollection PostEntityImages { get; set; }
        [DataMember] public EntityImageCollection PreEntityImages { get; set; }
        [DataMember] public Guid PrimaryEntityId { get; set; }
        [DataMember] public string PrimaryEntityName { get; set; }
        [DataMember] public Guid? RequestId { get; set; }
        [DataMember] public string SecondaryEntityName { get; set; }
        [DataMember] public ParameterCollection SharedVariables { get; set; }
        [DataMember] public Guid UserId { get; set; }
        [DataMember(Name = "ParentContext")] public CapturedPluginContext ParentCaptured { get; set; }
        [DataMember] public int Stage { get; set; }
        public IPluginExecutionContext ParentContext { get { return ParentCaptured; } }
    }

    internal sealed class ReplayTracingService : ITracingService
    {
        public void Trace(string format, params object[] args)
        {
            try { Console.WriteLine(args != null && args.Length > 0 ? string.Format(format, args) : format); }
            catch { Console.WriteLine(format); }
        }
    }

    // Throws a clear message if the plugin makes an org call — the profile captures those calls but this
    // harness doesn't re-serve them. Replace with your own mock (e.g. FakeXrmEasy) for org-dependent code.
    internal sealed class ReplayOrganizationService : IOrganizationService
    {
        private static Exception NotReplayed(string op)
        {
            return new NotSupportedException("Replay: the plugin called IOrganizationService." + op +
                " — this generated harness does not re-serve captured org calls. Replace DvptReplay.ReplayOrganizationService with a mock to exercise this path.");
        }
        public Guid Create(Entity entity) { throw NotReplayed("Create"); }
        public Entity Retrieve(string entityName, Guid id, ColumnSet columnSet) { throw NotReplayed("Retrieve"); }
        public void Update(Entity entity) { throw NotReplayed("Update"); }
        public void Delete(string entityName, Guid id) { throw NotReplayed("Delete"); }
        public OrganizationResponse Execute(OrganizationRequest request) { throw NotReplayed("Execute"); }
        public void Associate(string entityName, Guid entityId, Relationship relationship, EntityReferenceCollection relatedEntities) { throw NotReplayed("Associate"); }
        public void Disassociate(string entityName, Guid entityId, Relationship relationship, EntityReferenceCollection relatedEntities) { throw NotReplayed("Disassociate"); }
        public EntityCollection RetrieveMultiple(QueryBase query) { throw NotReplayed("RetrieveMultiple"); }
    }

    internal sealed class ReplayOrganizationServiceFactory : IOrganizationServiceFactory
    {
        public IOrganizationService CreateOrganizationService(Guid? userId) { return new ReplayOrganizationService(); }
    }

    internal sealed class ReplayServiceProvider : IServiceProvider
    {
        private readonly IPluginExecutionContext _context;
        private readonly ITracingService _tracing = new ReplayTracingService();
        public ReplayServiceProvider(IPluginExecutionContext context) { _context = context; }
        public object GetService(Type serviceType)
        {
            if (serviceType == typeof(IPluginExecutionContext) || serviceType == typeof(IExecutionContext)) return _context;
            if (serviceType == typeof(ITracingService)) return _tracing;
            if (serviceType == typeof(IOrganizationServiceFactory)) return new ReplayOrganizationServiceFactory();
            return null;
        }
    }

    public static class ProfileReplay
    {
        public static IPluginExecutionContext LoadContext(string profilePath)
        {
            var compressed = Convert.FromBase64String(File.ReadAllText(profilePath).Trim());
            string reportXml;
            using (var input = new MemoryStream(compressed))
            using (var deflate = new DeflateStream(input, CompressionMode.Decompress))
            using (var output = new MemoryStream())
            {
                deflate.CopyTo(output);
                reportXml = Encoding.UTF8.GetString(output.ToArray());
            }
            var contextXml = XDocument.Parse(reportXml).Descendants().First(e => e.Name.LocalName == "Context").Value;
            using (var reader = XmlReader.Create(new StringReader(contextXml)))
            {
                var serializer = new DataContractSerializer(typeof(object), new[] { typeof(CapturedPluginContext) });
                return (IPluginExecutionContext) serializer.ReadObject(reader);
            }
        }

        public static IServiceProvider CreateServiceProvider(IPluginExecutionContext context)
        {
            return new ReplayServiceProvider(context);
        }

        // The profile lives in <workspace>/profiles; walk up from the test bin so it's found regardless
        // of build configuration / TFM folder depth.
        public static string FindProfile(string fileName)
        {
            var dir = new DirectoryInfo(AppDomain.CurrentDomain.BaseDirectory);
            while (dir != null)
            {
                var candidate = Path.Combine(dir.FullName, "profiles", fileName);
                if (File.Exists(candidate)) return candidate;
                dir = dir.Parent;
            }
            throw new FileNotFoundException("Could not find profiles/" + fileName + " above the test directory.");
        }
    }
}
