// Generated by Dataverse PowerTools — replay of a captured plugin profile (#63/#210).
// Set breakpoints inside VoyageVistaSales.Plugins.voy_QuoteLineItem_PostCreate.Execute and DEBUG this test from the Test Explorer:
// it deserializes the captured execution context and invokes the plugin IN-PROCESS (no live org). If
// your plugin calls IOrganizationService, replace DvptReplay.ReplayOrganizationService with a mock
// (e.g. FakeXrmEasy) to exercise those branches.
using DvptReplay;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace VoyageVistaSales.Plugins.Tests
{
    [TestClass]
    public class Replay_voy_QuoteLineItem_PostCreate_20260921092022
    {
        [TestMethod]
        public void ReplayCapturedProfile()
        {
            var context = ProfileReplay.LoadContext(ProfileReplay.FindProfile("VoyageVistaSales.Plugins.voy_QuoteLineItem_PostCreate_20260917-112701.profile"));
            var plugin = new VoyageVistaSales.Plugins.CalculateQuoteTotal(null, null);
            plugin.Execute(ProfileReplay.CreateServiceProvider(context));
        }
    }
}
