adx_contentdisposition: 756150000
adx_enabletracking: false
adx_excludefromsearch: false
adx_hiddenfromsitemap: false
adx_name: Product image 1.png
adx_parentpageid: 7ec9c927-10e8-4ca0-8e5b-c12effc93f7a
adx_partialurl: Product image 1.png
adx_publishingstateid: cd455d7d-f6bf-4090-9ead-f8991dfe20e5
adx_webfileid: 0fb1bc5b-4377-4cac-8296-2021e4ba26b8
annotationid: 6783bfd8-98bc-f111-aaaf-7ced8d759cbe
filename: Product image 1.png
isdocument: true
mimetype: image/png
objectid: 0fb1bc5b-4377-4cac-8296-2021e4ba26b8
objecttypecode: adx_webfile
