#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: Microsoft.Xrm.Sdk.Client.ProxyTypesAssemblyAttribute()]

namespace VoyageVistaSales.Plugins.Models
{
	
	
	/// <summary>
	/// Represents a source of entities bound to a Dataverse service. It tracks and manages changes made to the retrieved entities.
	/// </summary>
	public partial class XrmSvc : Microsoft.Xrm.Sdk.Client.OrganizationServiceContext
	{
		
		/// <summary>
		/// Constructor.
		/// </summary>
		public XrmSvc(Microsoft.Xrm.Sdk.IOrganizationService service) : 
				base(service)
		{
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="VoyageVistaSales.Plugins.Models.Account"/> entities.
		/// </summary>
		public System.Linq.IQueryable<VoyageVistaSales.Plugins.Models.Account> AccountSet
		{
			get
			{
				return this.CreateQuery<VoyageVistaSales.Plugins.Models.Account>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="VoyageVistaSales.Plugins.Models.Contact"/> entities.
		/// </summary>
		public System.Linq.IQueryable<VoyageVistaSales.Plugins.Models.Contact> ContactSet
		{
			get
			{
				return this.CreateQuery<VoyageVistaSales.Plugins.Models.Contact>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="VoyageVistaSales.Plugins.Models.voy_Quote"/> entities.
		/// </summary>
		public System.Linq.IQueryable<VoyageVistaSales.Plugins.Models.voy_Quote> voy_QuoteSet
		{
			get
			{
				return this.CreateQuery<VoyageVistaSales.Plugins.Models.voy_Quote>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="VoyageVistaSales.Plugins.Models.voy_QuoteLineItem"/> entities.
		/// </summary>
		public System.Linq.IQueryable<VoyageVistaSales.Plugins.Models.voy_QuoteLineItem> voy_QuoteLineItemSet
		{
			get
			{
				return this.CreateQuery<VoyageVistaSales.Plugins.Models.voy_QuoteLineItem>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="VoyageVistaSales.Plugins.Models.voy_TravelInquiry"/> entities.
		/// </summary>
		public System.Linq.IQueryable<VoyageVistaSales.Plugins.Models.voy_TravelInquiry> voy_TravelInquirySet
		{
			get
			{
				return this.CreateQuery<VoyageVistaSales.Plugins.Models.voy_TravelInquiry>();
			}
		}
		
		/// <summary>
		/// Gets a binding to the set of all <see cref="VoyageVistaSales.Plugins.Models.voy_TravelProduct"/> entities.
		/// </summary>
		public System.Linq.IQueryable<VoyageVistaSales.Plugins.Models.voy_TravelProduct> voy_TravelProductSet
		{
			get
			{
				return this.CreateQuery<VoyageVistaSales.Plugins.Models.voy_TravelProduct>();
			}
		}
	}
}
#pragma warning restore CS1591
