#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyageVistaSales.Plugins.Models
{
	
	
	/// <summary>
	/// Type of activity.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum activitypointer_activitytypecode
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Fax = 4204,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PhoneCall = 4210,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Letter = 4207,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		RecurringAppointment = 4251,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Teamschat = 10270,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InviteRedemption = 10442,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PortalComment = 10443,
	}
}
#pragma warning restore CS1591
