#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyageVistaSales.Plugins.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum httpmethod
	{
		
		/// <summary>
		/// GET Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GET = 0,
		
		/// <summary>
		/// POST Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		POST = 1,
		
		/// <summary>
		/// PUT Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PUT = 2,
		
		/// <summary>
		/// PATCH Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PATCH = 3,
		
		/// <summary>
		/// DELETE Method
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		DELETE = 4,
	}
}
#pragma warning restore CS1591
