#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyageVistaSales.Plugins.Models
{
	
	
	/// <summary>
	/// List of Mobile Offline Enabled Entities.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum mobileofflineenabledentities
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Account = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Contact = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Note = 5,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		User = 8,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Team = 9,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Attachment = 1001,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Queue = 2020,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueueItem = 2029,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Appointment = 4201,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Email = 4202,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Task = 4212,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SLAKPIInstance = 9752,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ActivityFileAttachment = 10269,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleImage = 10278,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		KnowledgeArticleAttachment = 10284,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationDataSyncFnoState = 10317,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OrganizationDataSyncState = 10318,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		ImageDescriptor = 1007,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		NativeExtension = 10342,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerAppsWrapBuild = 10343,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		PowerPagesDDOSAlert = 10486,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity5af3c8a830 = 10505,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitycbd3796509 = 10525,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitya0f9dd4841 = 10543,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityd3abc30b22 = 10561,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity22e3bd074f = 10574,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitydc3565ceed = 10587,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityfc5b3a71d5 = 10597,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity0ba6d7830c = 10599,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity9619907365 = 10600,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity622eff85f2 = 10601,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity65c7d88854 = 10602,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity6b23d4690f = 10603,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity1497e807cc = 10604,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityf370b40824 = 10605,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity66fe396991 = 10606,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		GeolocationRecord = 10610,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityeb19e5c360 = 10614,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity3448740f52 = 10631,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentity4e3fcc7151 = 10646,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentityfc28f5adf6 = 10660,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		InquirytoQuote = 10761,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Reserveentitye60e601dd0 = 10674,
	}
}
#pragma warning restore CS1591
