#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyageVistaSales.Plugins.Models
{
	
	
	/// <summary>
	/// AI Model Task Type
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum msdyn_aimodeltasktype
	{
		
		/// <summary>
		/// None
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		None = 100000000,
		
		/// <summary>
		/// QueryBoosting
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		QueryBoosting = 100000001,
		
		/// <summary>
		/// Classification
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Classification = 100000002,
	}
}
#pragma warning restore CS1591
