#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyageVistaSales.Plugins.Models
{
	
	
	/// <summary>
	/// Types of reports.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum optionset_runreport
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allapplicablerecords = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Theselectedrecords = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Allrecordsonallpagesincurrentview = 1,
	}
}
#pragma warning restore CS1591
