#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyageVistaSales.Plugins.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum restapiauthtype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OAuth2 = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		EntraSSO = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		APIKey = 2,
	}
}
#pragma warning restore CS1591
