#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyageVistaSales.Plugins.Models
{
	
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum servertype
	{
		
		/// <summary>
		/// Server for Agent 365
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Agent365 = 0,
	}
}
#pragma warning restore CS1591
