#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyageVistaSales.Plugins.Models
{
	
	
	/// <summary>
	/// Shows the service type of the SharePoint site
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum sharepointsite_servicetype
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		SharePoint = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		OneDrive = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Sharedwithme = 2,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		MSTeams = 3,
	}
}
#pragma warning restore CS1591
