#pragma warning disable CS1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VoyageVistaSales.Plugins.Models
{
	
	
	/// <summary>
	/// Identifies where the social profile originated from, such as Twitter, or FaceBook.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum socialprofile_community
	{
		
		/// <summary>
		/// Facebook item.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Facebook = 1,
		
		/// <summary>
		/// Twitter.
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Twitter = 2,
		
		/// <summary>
		/// Other default
		/// </summary>
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Other = 0,
	}
}
#pragma warning restore CS1591
